name: CI

on: [push]

jobs:
  build-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Build
        run: $slnList = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $slnList) {dotnet build $file.FullName}
      - name: Run tests
        run: For (/R %%I in (*.sln)) do dotnet test %%I
